# fly.toml app configuration file for informativecourses

app = 'informativecourses'
primary_region = 'iad'

[build]
  # Add static file handling
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  # Add headers configuration
  [[http_service.headers]]
    [http_service.headers.values]
      X-Frame-Options = "SAMEORIGIN"
      Access-Control-Allow-Origin = "*"
      Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: *;"

# Add static file serving configuration
[[statics]]
  guest_path = "/app"
  url_prefix = "/"

[mount]
  source = "."
  destination = "/app"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024