# fly.toml app configuration file generated for informativecourses on 2025-02-27T05:01:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = 'informativecourses'
primary_region = 'sjc'
[build]
  dockerfile = "Dockerfile"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
  # Updated HTTP checks with longer timeouts and grace period

  [[services.http_checks]]
    path = "/"
    protocol = "http"
    port = 8080
    interval = "15s"
    timeout = "5s"
    grace_period = "30s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "data"
  destination = "/app/data"